### ISSUE TITLE
nbsp is not working

### ISSUE THREAD

**Issue by ai** [killbillsbor/babel-plugin-transform-typograf#6]
Input:

```js
    permissionDesc2: 'Запросите доступ у коллег, пригласивших вас в проект. ' +
                     'Или~попросите~их поправить нужные настройки.'
```

Output: 
![v8f8392](https://user-images.githubusercontent.com/19343/36570416-fd292808-1842-11e8-907f-b38eb0cdb07e.png)

@killbillsbor check new line after `Или`

**Comment by vrizo** [comment]
@ai,

Sorry for the late answer.

I tried to replicate the problem but with no luck. As I can see, there are `&nbsp;` in actual project so I suppose it works correctly. Did you use `I18N` variable in this case?

```html
<div class="css-folq41 e1nvojhh4">
  Возможно, вы&nbsp;опечатались,
  когда вводили ссылку проекта в&nbsp;
  адресной строке. Или&nbsp; авторизовались
  в&nbsp;Амплифере, используя не&nbsp;ту почту,
  на&nbsp;которую вас приглашали в&nbsp;проект.
</div>
```

Thanks!
